# Generated by Django 5.2.2 on 2025-07-10 03:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LembagaPendidikan',
            fields=[
                ('idlembaga', models.AutoField(db_column='idlembaga', primary_key=True, serialize=False)),
                ('nama_lembaga', models.CharField(max_length=255, unique=True)),
                ('alamat_lembaga', models.TextField(blank=True, null=True)),
                ('telepon_lembaga', models.CharField(blank=True, max_length=50, null=True)),
                ('email_lembaga', models.CharField(blank=True, max_length=100, null=True)),
                ('npsn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('kepala_lembaga', models.CharField(blank=True, max_length=255, null=True)),
                ('nipnuptk_kepala', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('logo_lembaga', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'lembaga_pendidikan',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('lembaga_admin', 'Lembaga Admin'), ('guru_individual', 'Guru Individual'), ('guru_lembaga', 'Guru Lembaga')], default='guru_individual', help_text='Peran pengguna dalam sistem', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('profile_foto', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', help_text='Hanya diisi jika role adalah lembaga_admin atau guru_lembaga, menandakan afiliasi admin/guru dengan lembaga tertentu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'app_users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('idguru', models.AutoField(primary_key=True, serialize=False)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nip', models.CharField(blank=True, max_length=20, null=True)),
                ('nuptk', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(db_comment='Status kepegawaian/mengajar guru (e.g., Aktif, Nonaktif, Cuti)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(db_column='user_iduser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guru',
            },
        ),
        migrations.CreateModel(
            name='Jeniskegiatanguru',
            fields=[
                ('idjeniskegiatanguru', models.AutoField(db_column='idjenisKegiatanGuru', primary_key=True, serialize=False)),
                ('namakegiatan', models.CharField(db_column='namaKegiatan', max_length=100)),
                ('iskbm', models.BooleanField(db_column='isKBM')),
                ('volumejam', models.DecimalField(blank=True, db_column='volumeJam', decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('guru_pembuat', models.ForeignKey(blank=True, db_column='guru_idguru_pembuat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.guru')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
            ],
            options={
                'db_table': 'jeniskegiatanguru',
                'unique_together': {('namakegiatan', 'lembaga', 'guru_pembuat')},
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('idkelas', models.AutoField(primary_key=True, serialize=False)),
                ('namakelas', models.CharField(blank=True, db_column='NamaKelas', max_length=50, null=True)),
                ('tingkat', models.IntegerField(choices=[(7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], db_comment='7,8,9,10,11,12')),
                ('jurusan', models.CharField(blank=True, choices=[('UMUM', 'Umum'), ('IPA', 'IPA'), ('IPS', 'IPS'), ('BAHASA', 'Bahasa'), ('LAINNYA', 'Lainnya')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('guru_pembuat', models.ForeignKey(blank=True, db_column='guru_idguru_pembuat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_dibuat_guru', to='kbm_core.guru')),
                ('guru_walikelas', models.ForeignKey(blank=True, db_column='guru_idguru', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.guru', verbose_name='Wali Kelas')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
            ],
            options={
                'db_table': 'kelas',
            },
        ),
        migrations.CreateModel(
            name='JadwalPelajaran',
            fields=[
                ('idjadwal', models.AutoField(primary_key=True, serialize=False)),
                ('hari_minggu', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=10)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('ruangan', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('status_jadwal', models.CharField(choices=[('Aktif', 'Aktif'), ('Nonaktif', 'Nonaktif'), ('Dibatalkan', 'Dibatalkan')], default='Aktif', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('guru', models.ForeignKey(db_column='guru_idguru', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.guru')),
                ('kelas', models.ForeignKey(db_column='kelas_idkelas', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.kelas')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
            ],
            options={
                'db_table': 'jadwal_pelajaran',
            },
        ),
        migrations.CreateModel(
            name='Kegiatankbm',
            fields=[
                ('idkegiatankbm', models.AutoField(db_column='idkegiatanKBM', primary_key=True, serialize=False)),
                ('tglkbm', models.DateField(db_column='tglKBM')),
                ('jamke', models.CharField(db_column='jamKe', max_length=45)),
                ('materiajar', models.CharField(db_column='materiAjar', max_length=255)),
                ('penugasan', models.CharField(blank=True, max_length=255, null=True)),
                ('catatantambahan', models.CharField(blank=True, db_column='catatanTambahan', max_length=255, null=True)),
                ('jumlahhadirpd', models.IntegerField(db_column='jumlahHadirPD')),
                ('statuskbm', models.CharField(db_column='statusKBM', default='selesai', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('guru', models.ForeignKey(db_column='guru_idguru', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.guru')),
                ('jadwal', models.ForeignKey(blank=True, db_column='jadwal_idjadwal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.jadwalpelajaran')),
                ('kelas', models.ForeignKey(db_column='kelas_idkelas', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.kelas')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
            ],
            options={
                'db_table': 'kegiatankbm',
            },
        ),
        migrations.CreateModel(
            name='Catatankegiatanguru',
            fields=[
                ('idcatatankegiatanguru', models.AutoField(db_column='idcatatanKegiatanGuru', primary_key=True, serialize=False)),
                ('tglkegiatan', models.DateField(db_column='tglKegiatan')),
                ('deskripsi', models.CharField(max_length=100)),
                ('voljam', models.DecimalField(db_column='volJam', decimal_places=2, max_digits=4)),
                ('outputkegiatan', models.CharField(blank=True, db_column='outputKegiatan', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('guru', models.ForeignKey(db_column='guru_idguru', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.guru')),
                ('jeniskegiatanguru', models.ForeignKey(db_column='jenisKegiatanGuru_idjenisKegiatanGuru', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.jeniskegiatanguru')),
                ('kegiatankbm', models.ForeignKey(blank=True, db_column='kegiatanKBM_idkegiatanKBM', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.kegiatankbm')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
            ],
            options={
                'db_table': 'catatankegiatanguru',
            },
        ),
        migrations.CreateModel(
            name='Matapelajaran',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namamapel', models.CharField(db_column='NamaMapel', max_length=100)),
                ('kodemapel', models.CharField(db_column='KodeMapel', max_length=45)),
                ('grupmapel', models.CharField(blank=True, db_column='GrupMapel', max_length=45, null=True)),
                ('kurikulum', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('guru_pembuat', models.ForeignKey(blank=True, db_column='guru_idguru_pembuat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapel_dibuat_guru', to='kbm_core.guru')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
            ],
            options={
                'db_table': 'matapelajaran',
                'unique_together': {('kodemapel', 'lembaga', 'guru_pembuat'), ('namamapel', 'lembaga', 'guru_pembuat')},
            },
        ),
        migrations.AddField(
            model_name='kegiatankbm',
            name='matapelajaran',
            field=models.ForeignKey(db_column='MataPelajaran_id', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.matapelajaran'),
        ),
        migrations.AddField(
            model_name='jadwalpelajaran',
            name='matapelajaran',
            field=models.ForeignKey(db_column='MataPelajaran_id', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.matapelajaran'),
        ),
        migrations.CreateModel(
            name='Elemencapaian',
            fields=[
                ('idelemencapaian', models.AutoField(db_column='idelemenCapaian', primary_key=True, serialize=False)),
                ('tingkatkelas', models.IntegerField(db_column='tingkatKelas')),
                ('kodecapaian', models.CharField(db_column='kodeCapaian', max_length=45)),
                ('deskripsielemen', models.CharField(db_column='deskripsiElemen', max_length=255)),
                ('materiesensi', models.CharField(db_column='materiEsensi', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('guru_pembuat', models.ForeignKey(blank=True, db_column='guru_idguru_pembuat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.guru')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
                ('matapelajaran', models.ForeignKey(db_column='MataPelajaran_id', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.matapelajaran')),
            ],
            options={
                'db_table': 'elemencapaian',
                'unique_together': {('kodecapaian', 'lembaga')},
            },
        ),
        migrations.CreateModel(
            name='Pesertadidik',
            fields=[
                ('idpesertadidik', models.AutoField(db_column='idpesertaDidik', primary_key=True, serialize=False)),
                ('namalengkappd', models.CharField(db_column='namaLengkapPD', max_length=255)),
                ('nis', models.CharField(blank=True, db_column='NIS', max_length=20, null=True)),
                ('nisn', models.CharField(blank=True, db_column='NISN', max_length=20, null=True)),
                ('gender', models.CharField(max_length=15)),
                ('tgllahir', models.DateField(blank=True, db_column='tglLahir', null=True)),
                ('jenis_siswa', models.CharField(choices=[('Reguler', 'Reguler'), ('VIP/Khusus', 'VIP/Khusus'), ('Beasiswa Penuh', 'Beasiswa Penuh'), ('Beasiswa Temporer', 'Beasiswa Temporer')], default='Reguler', max_length=50)),
                ('is_berkebutuhan_khusus', models.BooleanField(default=False)),
                ('status_pd', models.CharField(choices=[('Aktif', 'Aktif'), ('Lulus', 'Lulus'), ('Pindah', 'Pindah'), ('Drop Out', 'Drop Out')], db_column='status_pd', default='Aktif', max_length=50)),
                ('tgl_lulus', models.DateField(blank=True, db_column='tgl_lulus', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('guru_pembuat', models.ForeignKey(blank=True, db_column='guru_idguru_pembuat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siswa_dibuat_guru', to='kbm_core.guru')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
            ],
            options={
                'db_table': 'pesertadidik',
                'unique_together': {('nis', 'lembaga', 'guru_pembuat'), ('nisn', 'lembaga', 'guru_pembuat')},
            },
        ),
        migrations.CreateModel(
            name='AlumniData',
            fields=[
                ('idalumni', models.AutoField(primary_key=True, serialize=False)),
                ('tahun_lulus', models.SmallIntegerField()),
                ('kontak_email_alumni', models.CharField(blank=True, max_length=255, null=True)),
                ('kontak_telepon_alumni', models.CharField(blank=True, max_length=50, null=True)),
                ('pendidikan_lanjut', models.CharField(blank=True, max_length=255, null=True)),
                ('pekerjaan_saat_ini', models.CharField(blank=True, max_length=255, null=True)),
                ('catatan_alumni', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
                ('pesertadidik', models.OneToOneField(db_column='pesertaDidik_idpesertaDidik', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.pesertadidik')),
            ],
            options={
                'db_table': 'alumni_data',
            },
        ),
        migrations.CreateModel(
            name='Rpp',
            fields=[
                ('idrpp', models.AutoField(primary_key=True, serialize=False)),
                ('judulrpp', models.CharField(db_column='judulRPP', max_length=255)),
                ('tglpembuatan', models.DateField(db_column='tglPembuatan')),
                ('alokasiwaktu', models.DecimalField(db_column='alokasiWaktu', decimal_places=2, max_digits=4)),
                ('tujuanpembelajaran', models.TextField(db_column='tujuanPembelajaran')),
                ('materipembelajaran', models.TextField(db_column='materiPembelajaran')),
                ('kegiatanpembuka', models.TextField(db_column='kegiatanPembuka')),
                ('kegiataninti', models.TextField(db_column='kegiatanInti')),
                ('kegiatanpenutup', models.TextField(db_column='kegiatanPenutup')),
                ('penilaian', models.TextField()),
                ('refleksi', models.TextField(blank=True, null=True)),
                ('catatantambahan', models.TextField(blank=True, db_column='catatanTambahan', null=True)),
                ('statusrpp', models.CharField(choices=[('Draft', 'Draft'), ('Siap', 'Siap'), ('Terverifikasi', 'Terverifikasi')], db_column='statusRPP', default='Draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('guru', models.ForeignKey(db_column='guru_idguru', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.guru')),
                ('kelas', models.ForeignKey(db_column='kelas_idkelas', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.kelas')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
                ('matapelajaran', models.ForeignKey(db_column='MataPelajaran_id', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.matapelajaran')),
            ],
            options={
                'db_table': 'rpp',
            },
        ),
        migrations.CreateModel(
            name='Sumberrpp',
            fields=[
                ('idsumberrpp', models.AutoField(db_column='idsumberRPP', primary_key=True, serialize=False)),
                ('jenissumber', models.CharField(db_column='jenisSumber', max_length=100)),
                ('deskripsisumber', models.TextField(blank=True, db_column='deskripsiSumber', null=True)),
                ('urlfile', models.CharField(blank=True, db_column='urlFile', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
                ('rpp', models.ForeignKey(db_column='rpp_idrpp', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.rpp')),
            ],
            options={
                'db_table': 'sumberrpp',
            },
        ),
        migrations.CreateModel(
            name='Tahunajaran',
            fields=[
                ('idtahunajaran', models.AutoField(db_column='idTahunAjaran', primary_key=True, serialize=False)),
                ('tahunajaran', models.CharField(blank=True, db_column='TahunAjaran', max_length=60, null=True)),
                ('tglmulai', models.DateField(blank=True, db_column='TglMulai', null=True)),
                ('tglselesai', models.DateField(blank=True, db_column='TglSelesai', null=True)),
                ('isactive', models.BooleanField(db_column='isActive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('guru_pembuat', models.ForeignKey(blank=True, db_column='guru_idguru_pembuat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tahunajaran_dibuat_guru', to='kbm_core.guru')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
            ],
            options={
                'db_table': 'tahunajaran',
                'unique_together': {('tahunajaran', 'lembaga', 'guru_pembuat')},
            },
        ),
        migrations.AddField(
            model_name='rpp',
            name='tahunajaran',
            field=models.ForeignKey(db_column='TahunAjaran_idTahunAjaran', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.tahunajaran'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='tahunajaran',
            field=models.ForeignKey(db_column='TahunAjaran_idTahunAjaran', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.tahunajaran'),
        ),
        migrations.AddField(
            model_name='jadwalpelajaran',
            name='tahunajaran',
            field=models.ForeignKey(db_column='TahunAjaran_idTahunAjaran', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.tahunajaran'),
        ),
        migrations.CreateModel(
            name='Tugastambahan',
            fields=[
                ('idtugastambahan', models.AutoField(db_column='idTugasTambahan', primary_key=True, serialize=False)),
                ('namatugastambahan', models.CharField(db_column='NamaTugasTambahan', max_length=70)),
                ('inisialtugastambahan', models.CharField(blank=True, db_column='InisialTugasTambahan', max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('guru_pembuat', models.ForeignKey(blank=True, db_column='guru_idguru_pembuat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tugas_tambahan_dibuat_guru', to='kbm_core.guru')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
            ],
            options={
                'db_table': 'tugastambahan',
                'unique_together': {('namatugastambahan', 'lembaga', 'guru_pembuat')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='kegiatankbm',
            unique_together={('guru', 'matapelajaran', 'kelas', 'tglkbm', 'jamke', 'lembaga')},
        ),
        migrations.CreateModel(
            name='GuruHasMatapelajaran',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('guru', models.ForeignKey(db_column='guru_idguru', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.guru')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
                ('matapelajaran', models.ForeignKey(db_column='MataPelajaran_id', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.matapelajaran')),
            ],
            options={
                'db_table': 'guru_has_matapelajaran',
                'unique_together': {('guru', 'matapelajaran', 'lembaga')},
            },
        ),
        migrations.CreateModel(
            name='Absensipd',
            fields=[
                ('idabsensipd', models.AutoField(db_column='idabsensiPD', primary_key=True, serialize=False)),
                ('statushadir', models.CharField(blank=True, db_column='statusHadir', max_length=20, null=True)),
                ('catatan', models.CharField(blank=True, max_length=50, null=True)),
                ('tglabsensi', models.DateField(db_column='tglAbsensi')),
                ('jenisabsensi', models.CharField(db_column='jenisAbsensi', default='Absensi KBM', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('kegiatankbm', models.ForeignKey(blank=True, db_column='kegiatanKBM_idkegiatanKBM', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.kegiatankbm')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
                ('pesertadidik', models.ForeignKey(db_column='pesertaDidik_idpesertaDidik', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.pesertadidik')),
            ],
            options={
                'db_table': 'absensipd',
                'unique_together': {('pesertadidik', 'kegiatankbm')},
            },
        ),
        migrations.CreateModel(
            name='Riwayatkelaspd',
            fields=[
                ('idriwayatkelaspd', models.AutoField(db_column='idriwayatKelasPD', primary_key=True, serialize=False)),
                ('tglmulai', models.DateField(db_column='tglMulai')),
                ('tglselesai', models.DateField(blank=True, db_column='tglSelesai', null=True)),
                ('ket', models.CharField(blank=True, max_length=65, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('kelas', models.ForeignKey(db_column='kelas_idkelas', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.kelas')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
                ('pesertadidik', models.ForeignKey(db_column='pesertaDidik_idpesertaDidik', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.pesertadidik')),
                ('tahunajaran', models.ForeignKey(db_column='TahunAjaran_idTahunAjaran', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.tahunajaran')),
            ],
            options={
                'db_table': 'riwayatkelaspd',
                'unique_together': {('pesertadidik', 'kelas', 'tahunajaran', 'lembaga')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='kelas',
            unique_together={('namakelas', 'tahunajaran', 'lembaga', 'guru_pembuat')},
        ),
        migrations.AlterUniqueTogether(
            name='jadwalpelajaran',
            unique_together={('guru', 'kelas', 'tahunajaran', 'hari_minggu', 'jam_mulai', 'lembaga')},
        ),
        migrations.CreateModel(
            name='Masatugastambahan',
            fields=[
                ('idmasatugastambahan', models.AutoField(db_column='idMasaTugasTambahan', primary_key=True, serialize=False)),
                ('tglmulaitugas', models.DateField(db_column='tglMulaiTugas')),
                ('tglselesaitugas', models.DateField(blank=True, db_column='tglSelesaiTugas', null=True)),
                ('statustugas', models.CharField(blank=True, db_column='statusTugas', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('guru', models.ForeignKey(db_column='guru_idguru', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.guru')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
                ('tahunajaran', models.ForeignKey(db_column='TahunAjaran_idTahunAjaran', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.tahunajaran')),
                ('tugastambahan', models.ForeignKey(db_column='TugasTambahan_idTugasTambahan', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.tugastambahan')),
            ],
            options={
                'db_table': 'masatugastambahan',
                'unique_together': {('guru', 'tugastambahan', 'tahunajaran', 'lembaga')},
            },
        ),
        migrations.CreateModel(
            name='GuruHasTugastambahan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('guru', models.ForeignKey(db_column='guru_idguru', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.guru')),
                ('lembaga', models.ForeignKey(blank=True, db_column='lembaga_idlembaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kbm_core.lembagapendidikan')),
                ('tugastambahan', models.ForeignKey(db_column='TugasTambahan_idTugasTambahan', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.tugastambahan')),
            ],
            options={
                'db_table': 'guru_has_tugastambahan',
                'unique_together': {('guru', 'tugastambahan', 'lembaga')},
            },
        ),
        migrations.CreateModel(
            name='ElemencapaianHasRpp',
            fields=[
                ('elemencapaian', models.OneToOneField(db_column='elemenCapaian_idelemenCapaian', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kbm_core.elemencapaian')),
                ('rpp', models.ForeignKey(db_column='rpp_idrpp', on_delete=django.db.models.deletion.CASCADE, to='kbm_core.rpp')),
            ],
            options={
                'db_table': 'elemencapaian_has_rpp',
                'unique_together': {('elemencapaian', 'rpp')},
            },
        ),
    ]
